### ISSUE TITLE
Requests not using set cookies if useWebKit is true

### ISSUE THREAD

**Issue by jpamarohorta** [react-native-cookies/cookies#104]
Hello, I was having an issue with the `clear` and `set` methods not seeming to have any effect on requests. After some testing I figure it out that this only happened if I was using the `useWebKit` param as true.

Any idea why that was happening? Thank you!

**Comment by jpamarohorta** [comment]
I'm sorry it was an unrelated problem tied up with the domain attribute. I'll close this issue.

**Comment by safaiyeh** [comment]
@jpamarohorta if you dont mind could you share what you bumped into just in case someone lands on this thread?

**Comment by jpamarohorta** [comment]
No problem. A change in the cookie domain coming from the backend from .XXXX.com to XXXX.com made the cookie not being used as a header in requests to XXXX.com after I set it via the `CookieManager.set` method.

In an initial debug it seemed the problem was being caused by the `useWebKit` parameter but in the end it was a false positive.
