### ISSUE TITLE
Android cookie not being stored properly

### ISSUE THREAD

**Issue by mitchldtn** [react-native-cookies/cookies#99]
Has anyone encountered a problem with android and cookies?

On login with iOS my cookie looks like this:
```
{"cid": {"domain": "localhost", "expires": "2045-01-09T21:03:25.000-06:00", "httpOnly": true, "name": "cid", "path": "/", "secure": false, "value": "s%3AjS9YNEst6i2qRWZO2gc_J3aZzRl8iuR5.nRxOSlQXPE9J9umD62YjsyW2Xy5LyjCBHNQXjtWDtEI", "version": "0"}}
```

Android was the same and was working fine until today. Now I'm getting:
```
{"cid": {"domain": null, "httpOnly": false, "name": "cid", "path": null, "secure": false, "value": "s%3AuG5P6uprqa4V8jecJxd8_fgLgDxpP40N.jrofH%2F24L2B%2FWVA6Gq8BLNwk%2BFY5RnXEbijjaqMKLtc"}}
```

Has anyone experienced this and knows how to fix it? The android app is unusable now.

**Comment by safaiyeh** [comment]
@mitchldtn was this working previously? Which version caused the regression?

**Comment by safaiyeh** [comment]
Also which version are you on

**Comment by sparachi** [comment]
I'm trying for the first time though, not sure if it worked earlier. But when I do CookieManager.set I see "path":null,"domain":null, even though they're set.

**Comment by mitchldtn** [comment]
> Also which version are you on

Sorry for the delay. 

"react-native": "0.63.4" and I was using the most recent version of this package. 

I actually converted my backend and frontend to using tokens in headers for authentication to get around this issue. 

I think it's an android issue and not sure the issue is due to this package so I will close this.

**Comment by SikoraKam** [comment]
Why did you close it? Your approach to change auth flow doesn't resolve this issue

https://github.com/react-native-cookies/cookies/issues/164

**Comment by cjhines** [comment]
This is still completely broken in latest release. Why did you close this @mitchldtn?

**Comment by mitchldtn** [comment]
> Why did you close it? Your approach to change auth flow doesn't resolve this issue
> 
> #164

> This is still completely broken in latest release. Why did you close this @mitchldtn?

I closed this because I stopped using the package entirely and resolved this by using local storage

**Comment by whirsheimer** [comment]
Same issue here

**Comment by chuckzee** [comment]
This issue is still happening as of Jan 17 '23.

**Comment by sufian1999** [comment]
Facing same issue.
